import type { IpcChannelPolicy, IpcChannelPrivilege, IpcChannelRule, IpcRegistrationKind } from './ipc-policy'
import type { WindowCapability } from './ipc-trust'

function rule(
  capabilities: readonly WindowCapability[],
  kind: IpcRegistrationKind,
  privilege: IpcChannelPrivilege
): IpcChannelRule {
  return Object.freeze({ capabilities: Object.freeze(capabilities), kind, privilege })
}

// This compile-time policy is deliberately self-contained. Importing the
// full-product inventory and filtering it at runtime would leave forbidden
// channel names in the packaged SSH-only artifact.
export const IPC_CHANNEL_POLICY = Object.freeze({
  'hermes:connection': rule(['primary', 'session', 'hud'], 'handle', 'gateway-runtime'),
  'hermes:connection:revalidate': rule(['primary', 'session', 'hud'], 'handle', 'gateway-runtime'),
  'hermes:backend:touch': rule(['primary', 'session', 'hud'], 'handle', 'gateway-runtime'),
  'hermes:api': rule(['primary', 'session', 'hud'], 'handle', 'gateway-api'),
  'hermes:gateway-proxy:start': rule(['primary', 'session', 'hud'], 'handle', 'gateway-runtime'),
  'hermes:gateway-proxy:send': rule(['primary', 'session', 'hud'], 'on', 'gateway-runtime'),
  'hermes:gateway-proxy:close': rule(['primary', 'session', 'hud'], 'on', 'gateway-runtime'),
  'hermes:boot-progress:get': rule(['primary'], 'handle', 'bootstrap'),
  'hermes:connection-config:get': rule(['primary'], 'handle', 'connection-config'),
  'hermes:connection-config:test': rule(['primary'], 'handle', 'connection-config'),
  'hermes:connection-config:save': rule(['primary'], 'handle', 'connection-config'),
  'hermes:connection-config:apply': rule(['primary'], 'handle', 'connection-config'),
  'hermes:ssh-config:hosts': rule(['primary'], 'handle', 'connection-config'),
  'hermes:ssh-config:resolve': rule(['primary'], 'handle', 'connection-config'),
  'hermes:profile:get': rule(['primary'], 'handle', 'profile-runtime'),
  'hermes:profile:set': rule(['primary'], 'handle', 'profile-runtime'),
  'hermes:data-url-read-max:get': rule(['primary'], 'handle', 'filesystem'),
  'hermes:data-url-read-max:set': rule(['primary'], 'handle', 'filesystem'),
  'hermes:readFileDataUrl': rule(['primary'], 'handle', 'filesystem'),
  'hermes:readFileDataUrlForAttach': rule(['primary'], 'handle', 'filesystem'),
  'hermes:readFileText': rule(['primary'], 'handle', 'filesystem'),
  'hermes:selectPaths': rule(['primary'], 'handle', 'filesystem'),
  'hermes:selectSavePath': rule(['primary'], 'handle', 'filesystem'),
  'hermes:saveImageFromUrl': rule(['primary'], 'handle', 'filesystem'),
  'hermes:saveImageBuffer': rule(['primary'], 'handle', 'filesystem'),
  'hermes:saveClipboardImage': rule(['primary'], 'handle', 'filesystem'),
  'hermes:normalizePreviewTarget': rule(['primary'], 'handle', 'filesystem'),
  'hermes:watchPreviewFile': rule(['primary'], 'handle', 'filesystem'),
  'hermes:watchDirectory': rule(['primary'], 'handle', 'filesystem'),
  'hermes:stopPreviewFileWatch': rule(['primary'], 'handle', 'filesystem'),
  'hermes:setting:defaultProjectDir:get': rule(['primary'], 'handle', 'filesystem'),
  'hermes:setting:defaultProjectDir:set': rule(['primary'], 'handle', 'filesystem'),
  'hermes:setting:defaultProjectDir:pick': rule(['primary'], 'handle', 'filesystem'),
  'hermes:workspace:sanitize': rule(['primary'], 'handle', 'filesystem'),
  'hermes:logs:reveal': rule(['primary'], 'handle', 'filesystem'),
  'hermes:logs:recent': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:readDir': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:gitRoot': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:reveal': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:openDir': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:desktopPluginsRoot': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:agentPluginsRoot': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:rename': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:writeText': rule(['primary'], 'handle', 'filesystem'),
  'hermes:fs:trash': rule(['primary'], 'handle', 'filesystem'),
  'hermes:git:worktreeList': rule(['primary'], 'handle', 'git'),
  'hermes:git:worktreeAdd': rule(['primary'], 'handle', 'git'),
  'hermes:git:worktreeRemove': rule(['primary'], 'handle', 'git'),
  'hermes:git:branchSwitch': rule(['primary'], 'handle', 'git'),
  'hermes:git:branchList': rule(['primary'], 'handle', 'git'),
  'hermes:git:baseBranchList': rule(['primary'], 'handle', 'git'),
  'hermes:git:repoStatus': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:list': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:diff': rule(['primary'], 'handle', 'git'),
  'hermes:git:fileDiff': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:stage': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:unstage': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:revert': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:revParse': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:commit': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:commitContext': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:push': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:shipInfo': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:prList': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:fetchPrComment': rule(['primary'], 'handle', 'git'),
  'hermes:git:review:createPr': rule(['primary'], 'handle', 'git'),
  'hermes:git:scanRepos': rule(['primary'], 'handle', 'git'),
  'hermes:terminal:start': rule(['primary'], 'handle', 'terminal'),
  'hermes:terminal:write': rule(['primary'], 'handle', 'terminal'),
  'hermes:terminal:resize': rule(['primary'], 'handle', 'terminal'),
  'hermes:terminal:cwd': rule(['primary'], 'handle', 'terminal'),
  'hermes:terminal:dispose': rule(['primary'], 'handle', 'terminal'),
  'hermes:openExternal': rule(['primary'], 'handle', 'external-open'),
  'hermes:openPreviewInBrowser': rule(['primary'], 'handle', 'external-open'),
  'hermes:requestMicrophoneAccess': rule(['primary'], 'handle', 'permission'),
  'hermes:window:readBelow': rule(['primary'], 'handle', 'permission'),
  'hermes:readClipboard': rule(['primary'], 'handle', 'clipboard'),
  'hermes:writeClipboard': rule(['primary'], 'handle', 'clipboard'),
  'hermes:vscode-theme:fetch': rule(['primary'], 'handle', 'host-integration'),
  'hermes:vscode-theme:search': rule(['primary'], 'handle', 'host-integration'),
  'hermes:deep-link-ready': rule(['primary'], 'handle', 'host-integration'),
  'hermes:notify': rule(['primary', 'session', 'hud'], 'handle', 'notification'),
  'hermes:window:openSession': rule(['primary'], 'handle', 'window-control'),
  'hermes:window:openInstance': rule(['primary'], 'handle', 'window-control'),
  'hermes:pet-overlay:open': rule(['primary', 'session'], 'handle', 'window-control'),
  'hermes:pet-overlay:close': rule(['primary', 'session', 'pet-overlay'], 'handle', 'window-control'),
  'hermes:pet-overlay:set-bounds': rule(['pet-overlay'], 'on', 'window-control'),
  'hermes:pet-overlay:ignore-mouse': rule(['pet-overlay'], 'on', 'window-control'),
  'hermes:pet-overlay:set-focusable': rule(['pet-overlay'], 'on', 'window-control'),
  'hermes:pet-overlay:control': rule(['pet-overlay'], 'on', 'window-control'),
  'hermes:pet-overlay:state': rule(['primary', 'session'], 'on', 'renderer-safe'),
  'hermes:hud:open': rule(['primary', 'session'], 'handle', 'window-control'),
  'hermes:hud:close': rule(['primary', 'session', 'hud'], 'handle', 'window-control'),
  'hermes:hud:vibrancy': rule(['hud'], 'handle', 'window-control'),
  'hermes:hud:ignore-mouse': rule(['hud'], 'on', 'window-control'),
  'hermes:hud:move-by': rule(['hud'], 'on', 'window-control'),
  'hermes:hud:set-bounds': rule(['hud'], 'on', 'window-control'),
  'hermes:hud:session': rule(['hud'], 'on', 'window-control'),
  'hermes:quick-entry:settings:get': rule(['primary'], 'handle', 'host-integration'),
  'hermes:quick-entry:settings:set': rule(['primary'], 'handle', 'host-integration'),
  'hermes:quick-entry:submit': rule(['quick-entry'], 'on', 'renderer-safe'),
  'hermes:quick-entry:dismiss': rule(['quick-entry'], 'on', 'renderer-safe'),
  'hermes:quick-entry:state': rule(['primary'], 'on', 'renderer-safe'),
  'hermes:find-in-page': rule(['primary', 'session', 'hud'], 'handle', 'renderer-safe'),
  'hermes:stop-find-in-page': rule(['primary', 'session', 'hud'], 'handle', 'renderer-safe'),
  'hermes:zoom:get': rule(['primary', 'session', 'hud'], 'handle', 'renderer-safe'),
  'hermes:zoom:set-percent': rule(['primary', 'session', 'hud'], 'on', 'renderer-safe'),
  'hermes:active-work': rule(['primary', 'session', 'hud'], 'on', 'renderer-safe'),
  'hermes:power-battery:get': rule(
    ['primary', 'session', 'hud', 'quick-entry', 'pet-overlay'],
    'handle',
    'renderer-safe'
  ),
  'hermes:version': rule(['primary', 'session', 'hud', 'quick-entry', 'pet-overlay'], 'handle', 'renderer-safe'),
  'hermes:ambient:claim': rule(['primary', 'session', 'hud'], 'handle', 'renderer-safe'),
  'hermes:wake-indicator:get': rule(['primary'], 'handle', 'renderer-safe'),
  'hermes:wake-indicator:set': rule(['primary'], 'on', 'host-integration'),
  'hermes:translucency': rule(['primary'], 'on', 'host-integration'),
  'hermes:keep-awake': rule(['primary'], 'on', 'host-integration'),
  'hermes:previewShortcutActive': rule(['primary', 'session'], 'on', 'renderer-safe'),
  'hermes:titlebar-theme': rule(['primary', 'session', 'hud', 'quick-entry', 'pet-overlay'], 'on', 'renderer-safe'),
  'hermes:native-theme': rule(['primary', 'session', 'hud', 'quick-entry', 'pet-overlay'], 'on', 'renderer-safe'),
  'hermes:logs:renderer-error': rule(['primary', 'session', 'hud', 'quick-entry', 'pet-overlay'], 'on', 'renderer-safe')
}) satisfies IpcChannelPolicy
